import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

df_sar_may = pd.read_csv("sar_may.csv", delim_whitespace=True)
df_sar_july = pd.read_csv("sar_july.csv", delim_whitespace=True)
df_modis_may = pd.read_csv("modis_may.csv", delim_whitespace=True)
df_modis_july = pd.read_csv("modis_july.csv", delim_whitespace=True)

fig, ax = plt.subplots(nrows=2, ncols=2, figsize=(12,12))
ax[0,0].plot(df_sar_may["pixel_no"], df_sar_may["mean"], color="blue", label="SAR, May")
ax[0,0].set_xlabel("Pixel")
ax[0,0].set_ylabel(r"$\sigma_0$")
ax[0,0].legend()
ax[0,0].grid()
ax[0,0].set_xlim(left=0, right=max(df_sar_may["pixel_no"]))
ax[0,1].plot(df_sar_july["pixel_no"], df_sar_july["mean"], color="blue", label="SAR, July")
ax[0,1].set_xlabel("Pixel")
ax[0,1].set_ylabel(r"$\sigma_0$")
ax[0,1].grid()
ax[0,1].legend()
ax[0,1].set_xlim(left=0, right=max(df_sar_july["pixel_no"]))
ax[1,0].plot(df_modis_may["pixel_no"], df_modis_may["mean"], color="blue", label="MODIS, May")
ax[1,0].set_xlabel("Pixel")
ax[1,0].set_ylabel("Virtual Red Brightness")
ax[1,0].grid()
ax[1,0].legend()
ax[1,0].set_xlim(left=0, right=max(df_modis_may["pixel_no"]))
ax[1,1].plot(df_modis_july["pixel_no"], df_modis_july["mean"], color="blue", label="MODIS, July")
ax[1,1].set_xlabel("Pixel")
ax[1,1].set_ylabel("Virtual Red Brightness")
ax[1,1].set_xlim(left=0, right=max(df_modis_july["pixel_no"]))
ax[1,1].grid()
ax[1,1].legend()
plt.savefig("sar-modis.png")